#!/usr/bin/env bash
# Install an "OffTheWire" command so the agent can be launched from anywhere.
#
#     ./scripts/install_launcher.sh
#     ./scripts/install_launcher.sh --name otw
#     ./scripts/install_launcher.sh --uninstall
#
# Writes a small launcher into ~/.local/bin, which is on the PATH of every
# mainstream distro's default shell profile. The launcher passes every
# argument straight through, and agent.py already defaults its workspace to
# ".", so the directory you launch from becomes the workspace.
#
# POSIX counterpart of install_launcher.ps1.

set -eu

NAME="OffTheWire"
BIN_DIR="${HOME}/.local/bin"
UNINSTALL=0

while [ $# -gt 0 ]; do
    case "$1" in
        --name) NAME="$2"; shift ;;
        --bin-dir) BIN_DIR="$2"; shift ;;
        --uninstall) UNINSTALL=1 ;;
        *) echo "unknown option: $1" >&2; exit 2 ;;
    esac
    shift
done

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PYTHON="$ROOT/.venv/bin/python"
ENTRY="$ROOT/src/agent.py"
TARGET="$BIN_DIR/$NAME"

if [ "$UNINSTALL" = 1 ]; then
    if [ -e "$TARGET" ]; then rm "$TARGET" && echo "Removed $TARGET"
    else echo "Nothing at $TARGET"; fi
    exit 0
fi

# --- preflight ---------------------------------------------------------------

for p in "$PYTHON" "$ENTRY"; do
    if [ ! -e "$p" ]; then
        echo "Missing: $p" >&2
        echo "Run this from the project after creating .venv." >&2
        exit 1
    fi
done

mkdir -p "$BIN_DIR"
case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *) echo "Note: $BIN_DIR is not on PATH in this shell." ;;
esac

# --- write the launcher ------------------------------------------------------

cat > "$TARGET" <<EOF
#!/usr/bin/env bash
# Launcher for the offline coding agent. Generated by install_launcher.sh.
# Absolute paths so it works from any directory without activating .venv.
exec "$PYTHON" "$ENTRY" "\$@"
EOF
chmod +x "$TARGET"

echo "Installed $TARGET"
echo
echo "Use it from any directory:"
echo "  cd ~/some/project"
echo "  $NAME                 # that folder becomes the workspace"
echo "  $NAME --save          # keep the conversation"
echo "  $NAME --web --yes"
echo
echo "Open a new terminal if the command is not found immediately."
