<#
    Install an "OffTheWire" command so the agent can be launched from anywhere.

        cd C:\some\project
        OffTheWire --resume

    Writes a small .cmd shim into a directory that is already on the user PATH,
    so no environment variables are modified. Windows commands are
    case-insensitive, so "offthewire" works too.

    The shim passes every argument straight through, and agent.py already
    defaults its workspace to ".", which means the directory you launch from
    becomes the workspace. That is why there is no path juggling here.

        .\scripts\install_launcher.ps1
        .\scripts\install_launcher.ps1 -Name codey
        .\scripts\install_launcher.ps1 -Uninstall
#>
param(
    [string]$Name = "OffTheWire",
    [string]$BinDir = "$env:LOCALAPPDATA\Microsoft\WindowsApps",
    [switch]$Uninstall
)

$ErrorActionPreference = "Stop"

$root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$python = Join-Path $root ".venv\Scripts\python.exe"
$entry = Join-Path $root "src\agent.py"
$target = Join-Path $BinDir "$Name.cmd"

if ($Uninstall) {
    if (Test-Path $target) { Remove-Item $target -Force; Write-Host "Removed $target" }
    else { Write-Host "Nothing at $target" }
    exit 0
}

# --- preflight -------------------------------------------------------------

foreach ($p in @($python, $entry)) {
    if (-not (Test-Path $p)) {
        Write-Host "Missing: $p" -ForegroundColor Red
        Write-Host "Run this from the project after creating .venv." -ForegroundColor Red
        exit 1
    }
}

if (-not (Test-Path $BinDir)) {
    Write-Host "Target directory does not exist: $BinDir" -ForegroundColor Red
    exit 1
}

$onPath = ($env:Path -split ';') -contains $BinDir.TrimEnd('\')
if (-not $onPath) {
    # not fatal -- the user may have chosen a custom dir deliberately
    Write-Host "Note: $BinDir is not on PATH in this shell." -ForegroundColor Yellow
}

# --- write the shim --------------------------------------------------------

$cmd = @"
@echo off
rem Launcher for the offline coding agent. Generated by install_launcher.ps1.
rem Absolute paths so it works from any directory and without activating .venv.
"$python" "$entry" %*
"@

$cmd | Out-File -FilePath $target -Encoding ascii -NoNewline
Write-Host "Installed $target" -ForegroundColor Green
Write-Host ""
Write-Host "Use it from any directory:" -ForegroundColor Green
Write-Host "  cd C:\some\project"
Write-Host "  $Name                 # that folder becomes the workspace"
Write-Host "  $Name --resume        # continue the last session"
Write-Host "  $Name --web --yes"
Write-Host ""
Write-Host "Open a NEW terminal if the command is not found immediately."
